### ISSUE TITLE
The individual search bar appears twice in the table header, if I enable "individual_filtering_position" => "both" or => "head".

### ISSUE THREAD

**Issue by stwe** [stwe/DatatablesBundle#157]
The individual search bar appears twice in the table header, if I enable "individual_filtering_position" => "both" or => "head". This only happens in the clientside mode!

![bug](https://cloud.githubusercontent.com/assets/2964748/8513338/62239c30-2367-11e5-9780-f8778e0678a0.JPG)

**Comment by dchabanenko** [comment]
This problem occurs because the selector $(selector + '_wrapper thead tr') returns two rows (expected one): one is the table names, another is hidden (with zero height). 

The simple solution might be to insert the filters row after the last row in header, like this:
$(selector + '_wrapper tfoot tr').clone().insertAfter($(selector + '_wrapper thead tr').last()); 
Please check the PR: https://github.com/stwe/DatatablesBundle/pull/169

**Comment by stwe** [comment]
Thanks. Very strange. Your solution only shows a single search bar in the head. But this will disappear after entering a character in a search form.

**Comment by dchabanenko** [comment]
I've tried to use first() instead of last() and it worked for me. Could you please check: https://github.com/stwe/DatatablesBundle/pull/172

**Comment by stwe** [comment]
many thanks :+1:
