### ISSUE TITLE
Support extensions

### ISSUE THREAD

**Issue by stephanvierkant** [stwe/DatatablesBundle#203]
I'd like to use some [Datatables Extensions](https://www.datatables.net/extensions/index). How do I add them using this Bundle?

When you add ``'button' => true`` to the ``$this->options->setOptions()`` method, you'll get an ``UndefinedOptionsException``. Should we add all possible extensions to the ``AllowedTypes()``?

**Comment by stephanvierkant** [comment]
@stwe What kind of comments do you expect from us?

**Comment by stwe** [comment]
I need feedback which extensions should be supported. So far, no one has asked for it.

**Comment by migmolrod** [comment]
If I understood it well, the now-deprecated TableTools plugin has been replaced by 'Buttons' and 'Select' plugins.

I'd like to see both of them in this bundle, honestly, but can be a ton of work.

The 'Buttons' plugin allow global buttons to save the table as CSV, PDF, etc or directly print it out. I think this could be the easier one.

The 'Select' plugin allow to select stuff not only in a per-row basis but also in a per-cell basis. This could be masively useful to make a table with inline-editable fields for our entities. Interesting at least.
I didn't take a look to the code base or the API documentation of the plugin but my bet is it will make heavy use of AJAX calls and it would be the hardest of the two.

**Comment by stephanvierkant** [comment]
@migmolrod Why do you think it's a ton of work? And why only Buttons and Select? There are many other extensions as well: http://datatables.net/extensions/index

**Comment by migmolrod** [comment]
Well, maybe it's I am really busy lately so pretty much everything seems a ton of work for me XD

**Comment by stephanvierkant** [comment]
I just forked the repo to make a PR. It's a bit more complicated then I thought (so @migmolrod maybe you're right). Feel tree to comment/commit: https://github.com/stwe/DatatablesBundle/compare/master...Cronius:master

I added an array to Features, so you can add the extensions to it. Maybe it should be in a seperate class when it's getting complicated. 

One of the issues is that you'll have to add `B` to the `sDom` parameter (http://datatables.net/extensions/buttons/examples/initialisation/simple.html), but `sDom` is ignored when `use_integration_options` is set to `true`. Any ideas?

**Comment by migmolrod** [comment]
It's a good starting point. But when I said it seemed a lot of work for me, it was because I was thinking in a very diferent way.
I was more on making an
```php
interface ExtensionInterface
```
with common properties (let's say name and options) and getters/setters to them.
Then
```php
class ButtonExtension implements ExtensionInterface {}
class SelectExtension implements ExtensionInterface {}
// etc
```
and on top of the common properties from the interface, each one adding specific properties and methods wrapping those in the extensions' APIs

Example:
http://datatables.net/reference/api/#buttons

I don't know if it's overkill or needed. Maybe for easy extensions like the Buttons one, yours is a viable way to do it. But in more complex like the Select one


Another little thing. Strictly speaking, there is no 'need' to allow changes in `sDom` if `use_integration_options` is enabled. Take a look at the Buttons reference -> Displaying the buttons section. There are two ways to do it, one called **dom parameter** and another one called **direct insertion**:


>### Direct insertion
If you are using one of the styling integration options, such as for Bootstrap, or you wish to have multiple button instances available, the buttons().container() method can be used to obtain a jQuery object that holds the container element of the button set.

So it can be done with the current behavior.

**Comment by stephanvierkant** [comment]
Thanks! I think we should do it a more simple (and flexible!) manner, so we don't have to modify this bundle every time there is a new extension.

I agree there is no need to allow changes to `sDom`, but it's a 'nice to have' feature. I changes my other issue from 'need to' -> 'useful'
