### ISSUE TITLE
Improve filters

### ISSUE THREAD

**Issue by DraCzris** [stwe/DatatablesBundle#29]
Enable (implement configuration wrapper) setting custom filter for individual columns.

Basic filters:
- LIKE search
- exact match search
- select with options (provided by array or by one-to-many entity relation)

Advanced filters:
- datetime
    - options: today, this week, this month, this year

**Comment by dchabanenko** [comment]
Hello! Could you please look at my implementation of custom filters: https://github.com/stwe/DatatablesBundle/pull/127 

You can check out these feature at your example project: https://github.com/dchabanenko/dtbundle-demo/tree/custom-filters

I'm looking forward for your comments or advises.

**Comment by stwe** [comment]
I'll take a look at this. Thank you.

**Comment by stwe** [comment]
Looks good. I'll merge this now. Two issues: In client-side mode nothing is filtered. The fields in the header must also be updated.

**Comment by dchabanenko** [comment]
Sorry about the delay. 
I have investigated client-side mode and noticed, that dropdown options should be equal to the actual outputed values, but not false or true in js. Using the options 

'filter_options' => ['' => 'Any', 'yes' => 'Yes', 'no' => 'No'],

instead of 

"filter_options" => ["1" => "Yes", "0" => "No"],

client-side filters works fine.

Here is the PR: https://github.com/stwe/DatatablesBundle/pull/132 You can check it working on my fork of the demo: https://github.com/dchabanenko/dtbundle-demo/tree/custom-filters
@stwe Thanks for your work!

**Comment by stwe** [comment]
@dchabanenko Thanks for contributing! :+1:
