### ISSUE TITLE
 not possible to set row.id in columnBuilder() 

### ISSUE THREAD

**Issue by ducho** [stwe/DatatablesBundle#460]
@stwe 
I didn't understand your reaction. Can you explain it?

I changed the action_string.html.twig template to: 

{% for key, value in action.attributes %}
        **{% if 'row.id' == value %}
            attributes += '{{ key }} = "' + {{ value }} + '" ';
        {% else %}**
            attributes += '{{ key }}="{{ value }}" ';
        {% endif %}
{% endfor %}

That's all!

And keep calm and close the repository ;) 
Your choice... 

-
It is precisely these stupid sayings , for which I now seriously considering to close the repository .
I do this in my spare time and it's free.

@ducho
Write your own bundle and save you stupid sayings .

**Comment by dnagirl** [comment]
What I found is that (in dev-master) if you set the rowId option, the property matching the value of the rowId option of that row's entity is used as the row id. e.g. (pseudocode)

```
rowId option = 'id'
<tr id={{entity.id}} />
```
Since the html standard requires all element ids to be unique, this might work as long as there is only one table on the page. Unfortunately, the html4 standard also requires element ids to start with a letter, so these row ids are only html5 compliant.

I'd like to suggest that row ids be namespaced by prefacing the id with the table id.  So instead of
`<tr id={{entity.id}} />` it would be `<tr id={{ datatable.id }}_{{entity.id}} />`. This would address the uniqueness issue and the html4 issue. And it would only require a small change to the row template.

**Comment by ducho** [comment]
@dnagirl I needed row.id as attribute "data-id" in action button. 
```
array(
    'route' => 'report_delete',
    'route_parameters' => array(
        'id' => 'id'
    ),
    'label' => '',
    'icon' => 'fa fa-stop-circle-o',
    'attributes' => array(
        'data-id' => 'row.id',
        'data-action' => 'cancel',
        'rel' => 'tooltip',
        'title' => $this->translator->trans('datatables.actions.cancel'),
        'class' => 'btn btn-default btn-xs btn-action',
        'role' => 'button'
    ),
),
```
result
`<a href="/admin/report/11" data-id="11" data-action="delete" rel="tooltip" title="Delete" class="btn btn-danger btn-xs btn-action" role="button"><i class="fa fa-times"></i></a>`

**Comment by dnagirl** [comment]
If the id is in an easily identifiable place, it's pretty straightforward javascript to grab it from there. Or you could extend the AbstractAction class to create your own action button with the attributes you need.
