### ISSUE TITLE
Button customization

### ISSUE THREAD

**Issue by fleskalebas** [stwe/DatatablesBundle#524]
How can one customize the excel export function with javasript functions?
See https://datatables.net/reference/button/excelHtml5#Customisation

I tried

```
'extensions' => array(
                'buttons' =>
                    array(
                        [
							"extend" => 'excel',
							"customize" => "function( xlsx ) {
                var sheet = xlsx.xl.worksheets['sheet1.xml'];
                $('row:first c', sheet).attr( 's', '42' );
            }"
						],
                        'pdf'
                    ),
                'responsive' => true
            )
```

```
 'extensions' => array(
     'buttons' =>
                    array(
                        [
							"extend" => 'excel',
							"customize" => ":excel.js.twig"
						],
                        'pdf'
                    ),
                'responsive' => true
            )
```
But it echos the function literally (ofcourse).

then I tried it with a template but that doesn't work either. How can we solve this?

**Comment by Oliver-Gibson** [comment]
Hi,

Assuming you are using v0.13 or similar. Take a look at https://github.com/stwe/DatatablesBundle/blob/v0.13/Resources/views/Datatable/features.html.twig

Because you are saying it is part of "buttons" but not defining any "action" content gets json encoded. You will most likely need to override this template to fit your case (see http://symfony.com/doc/current/templating/overriding.html)

**Comment by fleskalebas** [comment]
Thanks, will look into that when I continue working on my app, very busy at the moment and it works without the needed function :)

**Comment by stephanvierkant** [comment]
See #819
