### ISSUE TITLE
Export all or (Server Side Export)

### ISSUE THREAD

**Issue by ahmadzai** [stwe/DatatablesBundle#682]
hi all, 
The export buttons (csv, pdf and print) only export/print the visible data in the table (means only the current page of the table) , how can I print all the filtered data (or all the data). 

One option would be to do it in server side, so I tried that (read one closed issue), but I couldn't find how to add a topAction button, or any button and call the exportAction controller to create the export on the server side. 
Your help and ideas would really be appreciated!
Thanks

**Comment by msitruk** [comment]
I m really interested about this "issue" too ;)

**Comment by ahmadzai** [comment]
for the time being, I changed the length menu to include "All Records" option (it's value should be -1), so first the user should select "All records" and then export. However, for a huge number of records this is not an optimal solution.

**Comment by stephanvierkant** [comment]
Clients are often not able to export all data to a spreadsheet. The export buttons are highly irreliable.

I've created a 'bridge' between this bundle and [PhpExcel](https://github.com/PHPOffice/PHPExcel) in the past, but this bundle has had breaking changes since v1.0 and PhpExcel development has been stopped in favor of [PhpSpreadsheet](https://github.com/PHPOffice/PhpSpreadsheet).

I'm thinking of redevelop this bridge with the new stable version of this bundle and PhpSpreadsheet.

Unfortunately generating a spreadsheet is a slow process for both client and server, so offloading it to a background process seems the only option to me.

Any more ideas on this?

**Comment by ahmadzai** [comment]
@stephanvierkant thanks for your comment, actually I look at your previous solution but as you mentioned that solution unfortunately not working with the new version of DT. It would be great if you could redevelop that bridge with the new version of DT but using PhpExcel (however, if you could do it with PhpSpreadsheet that would also be very helpful, I will change it to PhpExcel as many developers are still using PhpExcel including myself). 
Generating spreadsheet in the background is also a good idea and I have seen it a project, when a user click download button it starts generating the spreadsheet on server and provide link to the user when it's done.

**Comment by roxid** [comment]
@ahmadzai To add a top action button just add this to your datatable class (>1.0, but it can also be done in 0.13):

```php
$this->extensions->set(array(
    'buttons' => array(
        'create_buttons' => array(
            array(
                'text' => 'csv export',
                'action' => array(
                    'template' => 'YourBundle::buttons_csv_export.js.twig',
                ),
            ),
        ),
    ),
));
```

```
{# buttons_csv_export.js.twig #}
function ( e, dt, node, config ) {
    /* here you could make a request to your controller route */
}
```

The export data can be provided in multiple ways, e.g. implement a custom DatatableFormatter (see `Sg\DatatablesBundle\Response\DatatableFormatter` for reference) and use that in your controller method to format the data for csv output.

**Comment by stwe** [comment]
@stephanvierkant yes, please with documentation
