### ISSUE TITLE
Symfony 4 support

### ISSUE THREAD

**Issue by secit-pl** [stwe/DatatablesBundle#709]
Symfony 4 is now in beta so it would bo nice if this bundle will be compatible with it.

**Comment by ProfM2** [comment]
I just built a new Symfony 4 project, and as of 28-Dec-2017, you have to include 'dev-master' branch.  It's working like a champ.

**Comment by stephanvierkant** [comment]
Any update on this? I don't want to rely on `dev-master`, so a new version tag would be fine if Symfony 4 is fully supported.

**Comment by secit-pl** [comment]
I'm also on dev-master and everything works so I think it's good moment to tag it for a new release.

**Comment by Seb33300** [comment]
New tag created

**Comment by secit-pl** [comment]
@stephanvierkant did you tried dev-master or the latest v1.0 release? Check the composer.json, those releases doesn't require the SensioGeneratorBundle.

**Comment by stephanvierkant** [comment]
It doesn't require it via composer.json explicitly, but it does when clearing cache. See #752.

You can't install `DatatablesBundle` (even dev-master) on Symfony 3.4 without SensioGeneratorBundle because of this implicit requirement. So I was wondering why you actually can install it with Symfony 4, but maybe that's because of Symfony 4 does not initialize commands when clearing cache.
