### ISSUE TITLE
Console commands doesn't work on Symfony 4

### ISSUE THREAD

**Issue by secit-pl** [stwe/DatatablesBundle#725]
```
#> php bin/console sg:datatable:generate AppBundle:Post


  There are no commands defined in the "sg:datatable" namespace.

  Did you mean this?
      doctrine:database
```

```
#> php bin/console sg:


  There are no commands defined in the "sg" namespace.
```

As you can see the bundle is registered in the kernel

```
#> php bin/console debug:config

Available registered bundles with their extension alias if available
====================================================================

 ---------------------------- ------------------------
  Bundle name                  Extension alias
 ---------------------------- ------------------------
...
  SgDatatablesBundle           sg_datatables
...
 ---------------------------- ------------------------
```

**Comment by elborio** [comment]
The command that used to create this extended the GenerateDoctrineCommand class, which was part of the sensio generator bundle which is not supported for symfony 4. I'm not sure how to fix this, but i'm sure others will.

class CreateDatatableCommand extends GenerateDoctrineCommand

^-- error is Undefined class here. Prolly not registering the command because GenerateDoctrineCommand used to extend from Command, but just changing it to Command won't fix the problem.

**Comment by infomaniac50** [comment]
I'm working on a fix for this here. https://github.com/infomaniac50/DatatablesBundle/tree/feature-maker

I need to test it some more but should be mostly complete. I'll submit a pull request when it's ready.

**Comment by AlexandraDeMatos** [comment]
Hi !
I know someone else tell that but I can't find response.
I'm on Symfony 4.1 and I can't use Datatable bundle

#> php bin/console sg:datatable:generate AppBundle:Post
There are no commands defined in the "sg:datatable" namespace.
Did you mean this?
doctrine:database

Thank's by advance
