### ISSUE TITLE
Question: Is it possible to use 2 different datatables in one controller? 

### ISSUE THREAD

**Issue by DennisBiesters** [stwe/DatatablesBundle#742]
I have one controller that creates 2 different datatables:

```
$links = $this->get('sg_datatables.factory')->create(CmsLinksDatatable::class);
$links->buildDatatable();
$sections = $this->get('sg_datatables.factory')->create(CmsSectieDatatable::class);
$sections->buildDatatable();
```

```
if ($request->isXmlHttpRequest()) {
      $responseService = $this->get('sg_datatables.response');
      $responseService->setDatatable($sections);
      //$responseService->setDatatable($links);
      $responseService->getDatatableQueryBuilder();

       return $responseService->getResponse();
}
```

I have to check which datatable the call came from and then set the correct one and return it i guess? But how? I tried request instanceof CmsLinksDatatable but that didn't work.

**Comment by k3ssen** [comment]
Rather than using the same controller-action for handling all request, you could use separate actions for handling your datatable response. 

For example, in your CmsLinksDatatable class you can set the ajax route inside the buildDatatable method:

	public function buildDatatable($options = [])
	{
	    //...
	    $this->ajax->set([
	        'type' => 'POST',
	        'url' => $this->router->generate('cms_links_results')
	    ]));
	    //...

Then, you can create an cmsLinksResult action for the 'cms_links_results' route name
